config/routes.rb
Rails.application.routes.draw do

  get 'listeners/index'

  resources :podcasts do
    resources :resources
  end

  resources :listeners
  
  get 'resources/index'

  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', shared: 'admins/shared', passwords: 'admins/passwords', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks', mailer: 'admins/mailer' }

  devise_scope :admin do 
    get '/' => 'admins/registrations#index'
  end

    get 'admins/sign_in' =>'podcasts#index'

  root 'listeners#index'

end

app/views/resources/_edit.html.erb
<%= form_for resources_index_path do |f| %>
  <%= f.text_field :title, placeholder: "Image/Article Title" %>
  <br />
  <br />
  <%= f.file_field :document, placeholder: "Upload Your Image/GIF"%>
  <br />
  <br />
  <%= f.text_field :link, placeholder: "Paste Article Link Here"%>
  <%= f.select :publication, options_for_select([["Washington Post", 1],["New York Times", 3],["The Atlantic", 4], ["Al Jazeera", 5], ["NPR", 6]]), {prompt: "Choose Your Source"}%>
  <br />
  <br />
  <%= f.text_field :time, placeholder: "When Should This Popup?"%>
  <%= f.hidden_field :podcast_id, :value => @podcast_id %>
  <br>
  <br>
  <%= f.submit "Upload Popup"%>

  <% end %>

app/views/resources/_form.html.erb
<div class="row" id="podcasts_block">
  <div class="five columns" id="inner_block">
    
  <%= form_for [@podcast, @resource] do |f| %>
  <div id="mini_border">
  <%= f.text_field :title, placeholder: "Image/Article Title" %>
  <br />
  <%= f.file_field :document, placeholder: "Upload Your Image/GIF"%>
  <br />
  <%= f.text_field :link, placeholder: "Paste Article Link Here"%>
  <%= f.select :publication, options_for_select([["Washington Post", 1],["New York Times", 3],["The Atlantic", 4], ["Al Jazeera", 5], ["NPR", 6]]), {prompt: "Choose Your Source"}%>
  <br />
  <%= f.text_field :time, placeholder: "When Should This Popup?"%>
  <%= f.hidden_field :podcast_id, :value => @podcast_id %>
  <br>
  <%= f.submit "Upload Popup"%>
    </div>
  <% end %>
  </div>
</div>

app/views/resources/edit.html.erb
<h1>Edit Your Popup</h1>

<%= render 'edit'%>

app/views/resources/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PopUp!</title>
</head>
<body>
  <nav>
    <span id="logo">Pop<span id="up">Up</span>!</span>
    <ul>
      <li><button class="nav_bar"><%= link_to 'Account Info', edit_admin_registration_path%></button></li>
      <li><button id="nav_bar"><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></button></li>
    </ul>
  </nav>

<div class="warpper_top">
    <div class="twelve columns" id="intro_holder">
      <div class="six columns" id="intro_block">
      <h2>Your PopUp Details</h2>
      </div>

      <div class="six columns" id="info_block">
      <p> Below are your PopUp! details for your podcasts.
      </div>
    </div>
  </div>


<br>
<br>
<div>
  <% if @articles.present? %>
    <% @articles.each do |article|%>
      <br>
      <br>
      <br>
      <br>
    <div class="twelve columns" id="articles">
    <strong>Title:</strong>
    <%= article.title %>
      <br />
      <br />
    <strong>Link</strong>
      <%= article.resource.link %><br>
      <%= article.content %>
      <br />
      <br />
    <button><%= link_to 'Edit', edit_podcast_resource_path(@podcast, article.resource)%></button>
    <button><%= link_to 'Delete', podcast_resource_path(@podcast, article.resource), method: :delete  %></button>
    <br />
    <br />
    </div> 
   <% end %>
  <% end %>
  <br>
  <button><%= link_to 'Profile', podcasts_path %></button>
</div>
<br />

</body>
</html>

app/views/resources/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PopUp!</title>
</head>
<body>

</body>
</html>

<h1>Create A New Episode Popup</h1>

<%= render 'form'%>

app/views/resources/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PopUp!</title>
</head>
<body>
  <nav>
    <span id="logo">Pop<span id="up">Up</span>!</span>
    <ul>
      <li><button><%= link_to 'Account Info', edit_admin_registration_path%></button></li>
      <li><button><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></button></li>
    </ul>
  </nav>

<div class="warpper_top">
    <div class="twelve columns" id="intro_holder">
      <div class="six columns" id="intro_block">
      <h2>Your PopUp Details</h2>
      </div>

      <div class="six columns" id="info_block">
      <p> Info about how to edit Popups for Admins
      </div>
    </div>
  </div>


<br>
<br>
<div>
  <% if @articles.present? %>
    <% @articles.each do |article|%>
      <br>
      <br>
      <br>
      <br>
    <div class="twelve columns" id="articles">
    <strong>Title:</strong>
    <%= article.title %>
      <br />
      <br />
    <strong>Link</strong>
      <%= article.resource.link %><br>
      <%= article.content %>
      <br />
      <br />
    <button><%= link_to 'Edit', edit_podcast_resource_path(@podcast, article.resource)%></button>
    <button><%= link_to 'Delete', podcast_resource_path(@podcast, article.resource), method: :delete  %></button>
    <br />
    <br />
    </div> 
   <% end %>
  <% end %>
  <br>
  <button><%= link_to 'Profile', podcasts_path %></button>
</div>
<br />
</body>
</html>