config/routes.rb
Rails.application.routes.draw do

  get 'listeners/index'

  resources :podcasts do
    resources :resources
  end

  resources :listeners
  
  get 'resources/index'

  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', shared: 'admins/shared', passwords: 'admins/passwords', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks', mailer: 'admins/mailer' }

  devise_scope :admin do 
    get '/' => 'admins/registrations#index'
  end

    get 'admins/sign_in' =>'podcasts#index'

  root 'listeners#index'

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  belongs_to :admin
  has_many :resources

  # show audio
  has_attached_file :audio
  # :path => ":rails_root/public/system/audios/000"
  validates_attachment_presence :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
                                    # :message => 'file must be of filetype .mp3'

  validates_attachment_size :audio, :less_than => 50.megabytes                                    
  validates_presence_of :title

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  before_action :require_admin

  def index
    @podcasts = Podcast.where(:admin_id => current_admin)
    @podcast = Podcast.new
    # @podcasts = Podcasts.all
  end

  def show
    @podcasts = Podcast.where(:admin_id => current_admin)
    @podcast = Podcast.find(params[:id])
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)

    if @podcast.save
      redirect_to podcasts_path
    else
      render 'new' 
    end
  end

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])
      if @podcast.update(podcast_params.permit(:title, :audio, :length))
        redirect_to podcasts_path  
      else
        render 'edit'
      end
  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    redirect_to podcasts_path
  end

  private
    def require_admin
      if current_admin
        true
      else
        false
      end
    end

    def podcast_params
      params.require(:podcast).permit(:title, :audio, :length, :admin_id).merge(admin: current_admin)
    end

end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_form.html.erb
<div class="row" id="podcasts_block">
  <div class="five columns" id="inner_block">
<%= form_for @podcast do |f| %>
  <%= f.text_field :title, placeholder: "Episode Title" %>
  <br />
  <br />
  <%= f.file_field :audio, placeholder: "Upload Your Podcast"%>
  <br />
  <br />
  <%= f.text_field :length, placeholder: "Podcast Length"%>
  <br />
  <br />
  <%= f.submit "Upload Episode"%>

<% end %>

</div>
</div>

app/views/podcasts/account.html.erb
<div id="admin_info">
  <h2>Your account information:</h2>
  <br />
  <br />
  <div id="avatar">
    <!-- < % = image_tag @admin.avatar.url(: medium) % > -->
  </div>

</div>
<div>
  <% if @admin.present? %>
    <% @admin.each do |admin|%>
  <strong>Name:</strong>
  <%= admin.first_name %> <%= admin.last_name %>
  <br />
  <br />
  <strong>Email:</strong>
  <%= admin.email %>
  <br />
  <br />
  <strong>Password:</strong>
   Hidden for security
  <br>
  <br>
  <td><button><%= link_to 'Edit', edit_admin_registration_path %></button></td>
  <%end%>
  <%end%>
</div>

app/views/podcasts/edit.html.erb
<h1>Edit your Podcast Information</h1>

<%= render 'form'%>

app/views/podcasts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Popup!</title>
</head>
<body>
  <nav>
    <span id="logo">Pop<span id="up">Up</span>!</span>
    <ul>
      <li><button><%= link_to 'Account Info', edit_admin_registration_path%></button></li>
      <li><button><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></button></li>
    </ul>
  </nav>
  <div class="warpper_top">
    <div class="twelve columns" id="intro_holder">
      <div class="six columns" id="block_intro">
      <h2>Upload Your Podcast</h2>
      <button><%= link_to 'Add A Podcast', new_podcast_path %></button>
      </div>

      <div class="six columns" id="info_block">
      <p> You can upload and view all of your podcasts here. Related content can be added by creating a PopUp! PopUps will be displayed as the listener makes their way through your episode. 
      </div>
    </div>
  </div>

<br>
<br>
  <div class="row" id="podcasts_block">
  <div class="five columns" id="inner_block">
  <% if @podcasts.present? %>
    <% @podcasts.each do |podcast|%>
    <div id="mini_border">
      <!-- <strong>Title:</strong> -->
      <strong><%= podcast.title %></strong><br>
      <!-- <strong>File Name:</strong> -->
      <%= podcast.audio_file_name%><br>
       <%= audio_tag(podcast.audio.url, controls: true)%><br>
      <!-- <strong>Length:</strong> -->
      <!-- < % = podcast.length % ><br> -->
        <button><%= link_to 'Add Popup', new_podcast_resource_path(podcast) %></button>
        <button><%= link_to 'View Popup', podcast_resources_path(podcast) %></button>
        <button><%= link_to 'Edit', edit_podcast_path(podcast)%></button>
        <button><%= link_to 'Delete', podcast_path(podcast), method: :delete  %></button>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

</body>
</html>
 

app/views/podcasts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PopUp!</title>
</head>
<body>
  <div class="wrapper_top">
    <div class="twelve columns" id="pod_holder">
        <div class="six columns" id="pod_form">
          <h2>Upload Your Podcast</h2>
          <%= render 'form' %>
        </div>

        <div class="six columns" id="pod_block">
          <p> Upload your podcast here. Podcast audio must be in an mp3 format and cannot exceed 50 megabytes. Be sure to add your episode title.</p>
        </div>
      </div>
    </div>
</body>
</html>

app/views/podcasts/show.html.erb
<h1>Podcast details </h1>

  <strong>Title:</strong>
  <%= @podcast.title %><br>
  <strong>File Name:</strong>
  <%= @podcast.audio_file_name%><br>
  <strong>Length:</strong>
  <%= @podcast.length%><br>
<br />
<br />
<button><%= link_to 'Profile', podcasts_path %></button>